export enum Dim {
    ROW = 'ROW',
    COL = 'COL'
}

export enum Direction {
    DOWN,
    LEFT,
    RIGHT,
    UP
}

export enum RegExType {
    LONGEST_PALINDROME = 'LONGEST_PALINDROME',
    LONGEST_REPEAT = 'LONGEST_REPEAT',
    NEXT_SYMBOL = 'NEXT_SYMBOL',
    PREVIOUS_SYMBOL = 'PREVIOUS_SYMBOL',
    SYMBOL_ORDER = 'SYMBOL_ORDER',
    SYMBOL_POSITIONS = 'SYMBOL_POSITIONS',
    SYMBOL_SUBSET = 'SYMBOL_SUBSET'
}
